# Generated by Django 4.2.11 on 2024-04-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BladeMaterial',
            fields=[
                ('blade_material_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blade material',
                'verbose_name_plural': 'blade materials',
            },
        ),
        migrations.CreateModel(
            name='BladeShape',
            fields=[
                ('blade_shape_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blade shape',
                'verbose_name_plural': 'blade shapes',
            },
        ),
        migrations.CreateModel(
            name='BondingAgent',
            fields=[
                ('bonding_agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_friable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bonding agent',
                'verbose_name_plural': 'bonding agents',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('parent_brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_brands', to='stabby_web.brand')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CuttingAgent',
            fields=[
                ('cutting_agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cutting agent',
                'verbose_name_plural': 'cutting agents',
            },
        ),
        migrations.CreateModel(
            name='DeploymentType',
            fields=[
                ('deployment_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'deployment type',
                'verbose_name_plural': 'deployment types',
            },
        ),
        migrations.CreateModel(
            name='HandleMaterial',
            fields=[
                ('handle_material_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'handle material',
                'verbose_name_plural': 'handle materials',
            },
        ),
        migrations.CreateModel(
            name='Knife',
            fields=[
                ('knife_id', models.AutoField(db_column='knife_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('brand_notes', models.TextField(blank=True, null=True)),
                ('closed_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year_of_manufacture', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_purchase', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_new', models.BooleanField(default=True)),
                ('knife_type_notes', models.TextField(blank=True, null=True)),
                ('blade_material_notes', models.TextField(blank=True, null=True)),
                ('handle_material_notes', models.TextField(blank=True, null=True)),
                ('lock_type_notes', models.TextField(blank=True, null=True)),
                ('needs_work', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('blade_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.bladematerial')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stabby_web.brand')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.country')),
                ('deployment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.deploymenttype')),
                ('handle_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.handlematerial')),
            ],
            options={
                'verbose_name': 'knife',
                'verbose_name_plural': 'knives',
            },
        ),
        migrations.CreateModel(
            name='KnifeType',
            fields=[
                ('knife_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'knife type',
                'verbose_name_plural': 'knife types',
            },
        ),
        migrations.CreateModel(
            name='LockType',
            fields=[
                ('lock_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lock type',
                'verbose_name_plural': 'lock types',
            },
        ),
        migrations.CreateModel(
            name='Lubricant',
            fields=[
                ('lubricant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lubricant',
                'verbose_name_plural': 'lubricants',
            },
        ),
        migrations.CreateModel(
            name='Sharpener',
            fields=[
                ('sharpener_id', models.AutoField(db_column='sharpener_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('brand_notes', models.TextField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('bonding_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.bondingagent')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stabby_web.brand')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.country')),
                ('cutting_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.cuttingagent')),
                ('lubricant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.lubricant')),
            ],
            options={
                'verbose_name': 'sharpener',
                'verbose_name_plural': 'sharpeners',
            },
        ),
        migrations.CreateModel(
            name='SteelType',
            fields=[
                ('steel_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'steel type',
                'verbose_name_plural': 'steel types',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('uom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('work_log_id', models.AutoField(db_column='work_log_id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('knife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.knife')),
                ('sharpener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.sharpener')),
            ],
            options={
                'verbose_name': 'work log',
                'verbose_name_plural': 'work logs',
            },
        ),
        migrations.CreateModel(
            name='SteelManufacturer',
            fields=[
                ('steel_manufacturer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.country')),
            ],
            options={
                'verbose_name': 'steel manufacturer',
                'verbose_name_plural': 'steel manufacturers',
            },
        ),
        migrations.AddField(
            model_name='sharpener',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='sharpener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knife',
            name='knife_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.knifetype'),
        ),
        migrations.AddField(
            model_name='knife',
            name='lock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.locktype'),
        ),
        migrations.AddField(
            model_name='knife',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='knife',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knife',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.vendor'),
        ),
        migrations.AddField(
            model_name='bladematerial',
            name='steel_manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.steelmanufacturer'),
        ),
        migrations.AddField(
            model_name='bladematerial',
            name='steel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.steeltype'),
        ),
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('blade_id', models.AutoField(db_column='blade_id', primary_key=True, serialize=False)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length_cutting_edge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('blade_shape_notes', models.TextField(blank=True, null=True)),
                ('has_half_stop', models.BooleanField(default=False)),
                ('is_main_blade', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('blade_shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.bladeshape')),
                ('knife', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stabby_web.knife')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.unitofmeasure')),
            ],
            options={
                'verbose_name': 'blade',
                'verbose_name_plural': 'blades',
            },
        ),
    ]
