# Generated by Django 4.2.11 on 2024-04-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0002_rename_parent_brand_id_brand_parent_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bladeshape',
            name='blade_shape_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
