# Generated by Django 4.2.11 on 2024-05-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0004_alter_bladematerial_blade_material_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewBladeGrid',
            fields=[
                ('blade_id', models.BigIntegerField(db_column='blade_id', primary_key=True, serialize=False)),
                ('knife_id', models.BigIntegerField()),
                ('blade_shape', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=20)),
                ('length_cutting_edge', models.CharField(max_length=20)),
                ('has_half_stop', models.BooleanField(default=False)),
                ('is_main_blade', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'view_blade_grid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewKnifeGrid',
            fields=[
                ('knife_id', models.BigIntegerField(db_column='knife_id', primary_key=True, serialize=False)),
                ('knife', models.CharField(max_length=255, null=True)),
                ('knife_type', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('num_of_blades', models.IntegerField(null=True)),
                ('blade_material', models.CharField(max_length=255, null=True)),
                ('handle_material', models.CharField(max_length=255, null=True)),
                ('lock_type', models.CharField(max_length=255, null=True)),
                ('deployment_type', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('needs_work', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'view_knife_grid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSharpenerGrid',
            fields=[
                ('sharpener_id', models.AutoField(db_column='sharpener_id', primary_key=True, serialize=False)),
                ('sharpener', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('cutting_agent', models.CharField(max_length=255)),
                ('bonding_agent', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255, null=True)),
                ('is_friable', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'view_sharpener_grid',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='blade',
            name='blade_shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.bladeshape'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='blade_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.bladematerial'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.country'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='deployment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.deploymenttype'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='handle_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.handlematerial'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='knife_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.knifetype'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='lock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.locktype'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.vendor'),
        ),
        migrations.AlterField(
            model_name='sharpener',
            name='bonding_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.bondingagent'),
        ),
        migrations.AlterField(
            model_name='sharpener',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.country'),
        ),
        migrations.AlterField(
            model_name='sharpener',
            name='cutting_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.cuttingagent'),
        ),
        migrations.AlterField(
            model_name='sharpener',
            name='lubricant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.lubricant'),
        ),
    ]
