# Generated by Django 4.2.11 on 2024-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0006_alter_blade_length_alter_blade_length_cutting_edge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='is_main_blade',
            field=models.BooleanField(default=False),
        ),
    ]
