# Generated by Django 4.2.11 on 2024-05-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0007_alter_blade_is_main_blade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(db_column='photo_id', primary_key=True, serialize=False)),
                ('photo_path', models.ImageField(upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('knife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.knife')),
                ('sharpener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.sharpener')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
