# Generated by Django 5.0.6 on 2024-05-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0008_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
