# Generated by Django 5.0.6 on 2024-05-18 23:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0009_rename_photo_path_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=85, scale=None, size=[800, 600], upload_to='images/'),
        ),
    ]
