# Generated by Django 5.0.6 on 2024-05-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0014_alter_photo_knife_alter_photo_sharpener'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-create_date'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='knife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='stabby_web.knife'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sharpener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='stabby_web.sharpener'),
        ),
    ]
