# Generated by Django 5.0.6 on 2024-06-04 21:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0016_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1200, 900], upload_to='images/'),
        ),
    ]
