# Generated by Django 5.0.6 on 2024-06-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0017_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bladematerial',
            name='steel_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.steelmanufacturer'),
        ),
    ]
