# Generated by Django 5.0.6 on 2024-06-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0018_alter_bladematerial_steel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bladematerial',
            name='steel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stabby_web.steeltype'),
        ),
    ]
