# Generated by Django 5.0.6 on 2024-06-14 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0019_alter_bladematerial_steel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='knife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blades', to='stabby_web.knife'),
        ),
    ]
