# Generated by Django 5.0.6 on 2024-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0020_alter_blade_knife'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPurchaseDate',
            fields=[
                ('last_purchase_date_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_purchase_date', models.DateField()),
            ],
            options={
                'verbose_name': 'last_purchase_date',
            },
        ),
    ]
