# Generated by Django 5.0.6 on 2024-07-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0021_lastpurchasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSteelTypeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'view_steel_type_chart',
                'managed': False,
            },
        ),
    ]
