# Generated by Django 5.0.6 on 2024-07-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0022_viewsteeltypechart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewSteelTypeChart',
        ),
    ]
