# Generated by Django 5.2.1 on 2026-01-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stabby_web', '0025_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='knife',
            name='has_pocket_clip',
            field=models.BooleanField(default=False),
        ),
    ]
