import '@popperjs/core';
import * as bootstrap from 'bootstrap';
import * as agGrid from 'ag-grid-community';
import * as agCharts from 'ag-charts-community';
import * as constants from './constants';
import * as enums from './enums';
import * as redirect_handler from './redirect-handler';
import * as copy_handler from './copy-handler';
import * as delete_handler from './delete-handler';
import * as ajax_handler from './ajax-handler';
import * as chart_loader from './chart-loader';
import * as grid_loader from './grid-loader';
import * as date_picker_handler from './date-picker-handler';
import * as popover_handler from './popover-handler';
import './click-handler';
import './page-handler';
import '../styles/styles.scss';
import './toast-handler';
import { chart_data_model } from './models/chart-data-model';
import { template_variable_model } from './models/template-variable.model';
import { view_knife_grid_model } from './models/view-knife-grid.model';
import { view_sharpener_grid_model } from './models/view-sharpener-grid.model';
import { view_blade_grid_model } from './models/view-blade-grid.model';
import { work_log_model } from './models/work-log.model';

import { ModuleRegistry } from 'ag-grid-community';
import { AllCommunityModule } from 'ag-grid-community';
ModuleRegistry.registerModules([AllCommunityModule]);

export { bootstrap };
export { agCharts };
export { agGrid };
export { redirect_handler };
export { copy_handler };
export { delete_handler };
export { ajax_handler };
export { chart_loader };
export { grid_loader };
export { constants };
export { date_picker_handler };
export { enums };
export { chart_data_model };
export { popover_handler };
export { template_variable_model };
export { view_knife_grid_model };
export { view_sharpener_grid_model };
export { view_blade_grid_model };
export { work_log_model };
