GRANT ALL PRIVILEGES ON DATABASE db TO stabby_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO stabby_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO stabby_app;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO stabby_app;
GRANT USAGE, CREATE ON SCHEMA public TO stabby_app;